@id = 61f9b9a2-4694-4b24-84f1-d5bd017bfbf0
@host = http://localhost:4000/api

###

# Get all floras
GET {{host}}/flora HTTP/1.1
content-type: application/json

###

# Get a single flora
GET {{host}}/flora/{{id}} HTTP/1.1
content-type: application/json

###

# Add a new flora
POST {{host}}/flora HTTP/1.1
content-type: application/json

{
    "title": "test",
    "uses": "..."
}

###

# Update a flora
PUT {{host}}/flora/{{id}} HTTP/1.1
content-type: application/json

{
    "title": "test",
    "uses": "..."
}

###

# Delete a flora
DELETE {{host}}/flora/{{id}} HTTP/1.1
content-type: application/json